### ISSUE TITLE
creating a new folder in my drive 

### ISSUE THREAD

**Issue by mohammad-azzam-dev** [masbug/flysystem-google-drive-ext#102]
Hello, every time I refresh the token it is creating a new folder and using it as the FolderId even if I assigned one in the .env it still doesn't use the folder instead it uses the newly created one

**Comment by mohammad-azzam-dev** [comment]
after debugging some lines of code, please note that the root is being passed but it is not being executed buy the class when creating the object check the diagram below after dd() the object

![image1](https://user-images.githubusercontent.com/83841726/222342524-26652a55-d391-48e2-9b34-19717670d66d.png)
the code:
![image2](https://user-images.githubusercontent.com/83841726/222342694-dd7b90fa-165a-4e05-863d-a41eb612d2c8.png)

and please note that I took the folderId from the .env using the env() helper and set it inside the config file on runtime

**Comment by erikn69** [comment]
You should not use the folder id, you should use the directory name with all the path

Here is a demo: [laravel-google-drive-ext-demo](https://github.com/erikn69/laravel-google-drive-ext-demo), [GoogleDriveServiceProvider.php](https://github.com/erikn69/laravel-google-drive-ext-demo/blob/10.x/app/Providers/GoogleDriveServiceProvider.php)
