### ISSUE TITLE
Duplicate root directories created when instantiating the adapter

### ISSUE THREAD

**Issue by mikemilano** [masbug/flysystem-google-drive-ext#108]
A new `My_App_Root` directory is created each time I run the following code. I end up with multiple `My_App_Root` directories, with another being added each time I run the following code.

```
    $adapter = new \Masbug\Flysystem\GoogleDriveAdapter(
            $service,
            'My_App_Root',
            [
                'useDisplayPaths' => true,
                'teamDriveId' => '1ieb52EPLufHJrKIblaac4CYPLvtR91Rv'
            ]
        );
```

For example, the `teamDriveId` is a directory named `test`.

When I instantiate `$adapter` (And no other code after it), the following directory is created: `test/My_App_Root`.

Then if I run it again, a duplicate `My_App_Root` directory is created.

When viewing in Google Drive web interface, I see several `My_App_Root` directories in the `test` directory.

Am I doing something wrong? My goal is to list/read/write files to the `test` directory.

**Comment by parallels999** [comment]
> For example, the teamDriveId is a directory named test.

`teamDriveId` must be a shared drive, not a directory

Look at this demo https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d42a136fcfa8b2543f9484db80f629f7033c0ae1/routes/web.php#L42-L49

**Comment by mikemilano** [comment]
@parallels999 confirmed this was the issue.  Thank you!

In case anyone else comes across this in the future, shared drives are not included in the Google Business Starter plan. I had to upgrade to a Business Standard plan for the shared drive feature in order to use this package.

**Comment by parallels999** [comment]
Also you can use a directory as root folder, but it must be the display name, not the folder id
https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d42a136fcfa8b2543f9484db80f629f7033c0ae1/.env.example#L39
https://github.com/masbug/flysystem-google-drive-ext/blob/3f1d05a7b5b62333fea39555141617ba68a2b956/README.md?plain=1#L191
