### ISSUE TITLE
401 Request had invalid authentication credentials (laravel jobs)

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#109]
In my Laravel app, I noticed that after uploading files using the queue system for about an hour, I encounter the following error message:

```
{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "location": "Authorization",
        "locationType": "header"
      }
    ],
    "status": "UNAUTHENTICATED"
  }
}
```

I found that this issue is resolved by manually restarting the queue using the command `php artisan queue:restart`

It seems that the [refreshToken ](https://github.com/masbug/flysystem-google-drive-ext/blob/3f1d05a7b5b62333fea39555141617ba68a2b956/src/GoogleDriveAdapter.php#L338)replaces the refreshed token in memory, but since Laravel jobs run indefinitely, they do not detect changes until the queue is restarted manually. How can I address this issue?

**Comment by parallels999** [comment]
for me it is working on laravel jobs

**Comment by parallels999** [comment]
https://github.com/masbug/flysystem-google-drive-ext/issues/33 You already open an issue about this, and you confirmed that everything worked correctly in laravel jobs
https://developers.google.com/identity/sign-in/web/sign-in?hl=es-419

**Comment by foremtehan** [comment]
I encounter the same issue again and i don't know why, nmv

**Comment by parallels999** [comment]
maybe google changes something https://developers.google.com/identity/sign-in/web/sign-in?hl=es-419
Feel free to make a PR fixing it
