### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by RichardDight** [masbug/flysystem-google-drive-ext#112]
Hey guys, just wanted to confirm whether Laravel 10 is currently supported. Recently upgraded from 9 => 10 a few days ago and got this error during my backup cleanups:

`Unable to retrieve the last_modified for file at location: staging-backup-2023-04-09-04-00-49.zip.
backup::notifications.exception_message_trace
#0 /var/www/html/vendor/league/flysystem/src/UnableToRetrieveMetadata.php(29): League\Flysystem\UnableToRetrieveMetadata::create()
#1 /var/www/html/vendor/masbug/flysystem-google-drive-ext/src/GoogleDriveAdapter.php(863): League\Flysystem\UnableToRetrieveMetadata::lastModified()
#2 /var/www/html/vendor/masbug/flysystem-google-drive-ext/src/GoogleDriveAdapter.php(893): Masbug\Flysystem\GoogleDriveAdapter->fileAttributes()
#3 /var/www/html/vendor/league/flysystem/src/Filesystem.php(140): Masbug\Flysystem\GoogleDriveAdapter->lastModified()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(623): League\Flysystem\Filesystem->lastModified()`

Other than that I haven't ran into any others errors during backups. I've checked permissions, all good there. Perhaps a corrupt backup?

**Comment by cesarreyes3** [comment]
Hi, Feel free to make a PR with a fix

**Comment by erikn69** [comment]
https://github.com/erikn69/laravel-google-drive-ext-demo
Laravel 10.x is tested
