### ISSUE TITLE
Can't display paths, just IDs

### ISSUE THREAD

**Issue by lianee** [masbug/flysystem-google-drive-ext#114]
Using v2.2.2
Seems related to #94, except that I don't use Laravel, but [barryvdh/elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver), and this is for a personal drive, not team.

I also have the problem that listContents returns an empty list with useDisplayPaths set to true, and IDs when set to false.
I tried setting showDisplayPaths to true to no avail, and also all combinations I could think of, but I am not able to list the names of folders and files.

Here's the configuration I'm using, does anyone have any idea what's wrong?

```php
$GDclient = new \Google_Client();
$GDclient->setClientId('...');
$GDclient->setClientSecret('...');
$GDclient->refreshToken('...');

new \Masbug\Flysystem\GoogleDriveAdapter(
	new \Google_Service_Drive($GDclient),
	'root',                             
	[
//		'useHasDir'     => true,
//		'driveId'       => 'root',
//		'useDisplayPaths'       => false,
//		'showDisplayPaths'      => true,
	]
),
```

**Comment by masbug** [comment]
This adapter is specifically for laravel + flysystem. elFinder is unsupported. That being said the adapter was once based upon nao-pon/flysystem-google-drive which does support elfinder. Perhaps this might help: https://github.com/nao-pon/flysystem-google-drive?tab=readme-ov-file#usage-to-with-elfinder
