### ISSUE TITLE
 Argument #1 ($value) must be of type Countable|array, null given in GoogleDriveAdapter.php:1037

### ISSUE THREAD

**Issue by marhub** [masbug/flysystem-google-drive-ext#119]
Seems like `$file->getPermissions()`  is returning null when there are no permission.
When PHP is set to strict, that causes error to be thrown `Argument #1 ($value) must be of type Countable|array, null given in GoogleDriveAdapter.php:1037`.
This is catched in `GoogleDriveAdapter:436` and even when file was written, throws error that `[League\Flysystem\UnableToWriteFile] Unable to write file at location: 2024/1704150401_test.txt. Not able to write the file`.

**Comment by marhub** [comment]
i can see that it was fixed on 2.x-dev, but latest version does point to some old source ( v 2.2.2 )

**Comment by badcom** [comment]
Yes, they didn't tag the latest changes =/

I had to fork this repo to be able to use the latest changes

**Comment by masbug** [comment]
Release created.
