### ISSUE TITLE
Google Batch Request deprecated

### ISSUE THREAD

**Issue by erikn69** [masbug/flysystem-google-drive-ext#12]
Google has [deprecated use of batch requests](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html?utm_campaign=ei-jun23&utm_medium=api-error-message&utm_source=shared_proxy). Means this that any call to the getFileObject function is gonna  fails?

**Comment by masbug** [comment]
The batch API only got a new URL - API specific. See https://developers.google.com/drive/api/v3/batch
But since this lib is using google/apiclient all the required changes are made just by updating the projects to download a new version of google/apiclient.
