### ISSUE TITLE
Moving folders will fall into the trash 

### ISSUE THREAD

**Issue by hrnicek** [masbug/flysystem-google-drive-ext#122]
Hello everyone, 

If I want to move a folder to a folder, the folder gets deleted to the trash:

```
    Route::get('/move', function () {

    $directoryName = 'TEST';
    $directoryNameTo = 'TEST2';

    Storage::cloud()->makeDirectory($directoryName);
    Storage::cloud()->makeDirectory($directoryNameTo);

    Storage::cloud()->move($directoryName, $directoryNameTo);

    return 'Directory was renamed in Google Drive';
});
```

Anyone have a similar problem?

**Comment by erikn69** [comment]
[laravel-google-drive-ext-demo/routes/web.php#L142-L149](https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d42a136fcfa8b2543f9484db80f629f7033c0ae1/routes/web.php#L142-L149)

I always tried that demo and it worked correctly, I don't think anything has changed

**Comment by angeljqv** [comment]
Feel free to make a PR with the fix

**Comment by erikn69** [comment]
Hi, could you test #127
