### ISSUE TITLE
Allowed memory size issue

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#124]
I used to back up my databases using spatie/laravel-backup and this repo, but suddenly I encountered this error:

![Capture](https://github.com/masbug/flysystem-google-drive-ext/assets/53290883/eb4f10f4-9be2-47c8-b169-554d1a8999ca)

**Comment by parallels999** [comment]
[PHP Allowed memory size](https://www.google.com/search?q=PHP+Allowed+memory+size)
