### ISSUE TITLE
create,delete,rename folder,get folder listing and data using folder id instead of name ,to remove duplicacy of same folder name

### ISSUE THREAD

**Issue by monika-sha90** [masbug/flysystem-google-drive-ext#125]
I want to create.delete,rename folder using folder id and get content and listing of all folder

**Comment by parallels999** [comment]
https://github.com/masbug/flysystem-google-drive-ext/blob/26932161868b60e8bcb3fda978e478c0c250c971/src/GoogleDriveAdapter.php#L95
```php
'useDisplayPaths'   => false, 
```

**Comment by monika-sha90** [comment]
Thanks ,Its working

**Comment by angeljqv** [comment]
test
