### ISSUE TITLE
Rename Directory using laravel

### ISSUE THREAD

**Issue by monika-sha90** [masbug/flysystem-google-drive-ext#126]
Rename directory using directory id in laravel.

Storage::disk('google');
using this command

**Comment by angeljqv** [comment]
You could try `move`
[laravel-google-drive-ext-demo/routes/web.php#L146](https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d42a136fcfa8b2543f9484db80f629f7033c0ae1/routes/web.php#L146)
But with "directory id" maybe [nao-pon/flysystem-google-drive](https://github.com/nao-pon/flysystem-google-drive), 
everything is easier with virtual paths

Also if there is a bug, you could make a PR with the fix

**Comment by erikn69** [comment]
Hi, could you test #127

**Comment by monika-sha90** [comment]
No its not working.
I am using this to rename directory or folder or file 
 Storage::disk('google')->move('1eBA6ICIYymKpreWwoQoUfARCU_5Ovqkd','test');

**Comment by monika-sha90** [comment]
These are working in laravel--
$createDirectory = Storage::disk('google')->makeDirectory('Directory1'); 
$createSubDirectory = Storage::disk('google')->makeDirectory('1mRjuzvIFtATv4j7ky1GcKYLO9mihWq5n/task1'); 
$deleteDirectory = Storage::disk('google')->deleteDirectory('1Mzhig8KeIkhQIIay63ApfUKDUg_Be0LC');// folder id

**Comment by erikn69** [comment]
>No its not working.

you did something wrong, I have created the branch [laravel-google-drive-ext-demo/tree/no_virtual_paths](https://github.com/erikn69/laravel-google-drive-ext-demo/tree/no_virtual_paths)

And the demo it's working [laravel-google-drive-ext-demo/routes/web.php#L201-L220](https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d93c343ae2fb6c0f12d34ea046828edc7974490d/routes/web.php#L201-L220)
```php
$directoryName = 'test';

// First we need to create a directory to rename
Storage::disk('google')->makeDirectory($directoryName);

// Now find that directory and use its ID (path) to rename it
$dir = collect(Storage::disk('google')->listContents('/', false))
    ->first(fn (\League\Flysystem\StorageAttributes $file) =>
        $file->type() === 'dir' && $file->extraMetadata()['name'] === $directoryName
    ); // there can be duplicate file names!

if (! $dir) {
    return 'Directory "'.$directoryName.'" does not exist!';
}

Storage::disk('google')->move($dir->path(), 'new-test');
```
**RESULT:**
![image](https://github.com/masbug/flysystem-google-drive-ext/assets/4933954/7cca2fc5-4485-4350-a28d-1839d9756157)

you know how to use another branch in the vendor?
