### ISSUE TITLE
useDisplayPaths is false, but return original filename

### ISSUE THREAD

**Issue by deesouza-ps** [masbug/flysystem-google-drive-ext#128]
I have this code below.
Same the property `useDisplayPaths` with `false`, on upload return the original filename.

``` php
Storage::extend('google', function ($app, $config) {
	$client = new GoogleClient();
	$client->setClientId($config['clientId']);
	$client->setClientSecret($config['clientSecret']);
	$client->refreshToken($config['refreshToken']);

	$service = new GoogleServiceDrive($client);
	$adapter = new GoogleDriveAdapter($service, $config['folderId'], [
		'useDisplayPaths' => false,
	]);
	$driver = new Filesystem($adapter);

	return new FilesystemAdapter($driver, $adapter);
});
```

### Upload

```
$fileNameUpload = $fileUpload->storeAs('ID_PATH_GOOGLE_DRIVE', $fileName, 'google');
```

**Comment by erikn69** [comment]
the main functionality is `useDisplayPaths => true`, but:
[erikn69/laravel-google-drive-ext-demo/routes/web.php#L44-L48](https://github.com/erikn69/laravel-google-drive-ext-demo/blob/d93c343ae2fb6c0f12d34ea046828edc7974490d/routes/web.php#L44-L48)
[ivanvermeyen/laravel-google-drive-demo/routes/web.php#L74-L84](https://github.com/ivanvermeyen/laravel-google-drive-demo/blob/4d1c2a381ed0d978b6870a455869543c7b3cd471/routes/web.php#L74-L84)

Also feel free to open a PR

**Comment by angeljqv** [comment]
That is the [laravel expected behaivor](https://cdn.someecards.com/someecards/usercards/people-like-you-are-the-reason-shampoo-has-directions-f70da.png), this package works independently of Laravel

**Comment by deesouza-ps** [comment]
When `useDisplayPaths` is `true` should return filename original.
But, when `useDisplayPaths` is `false` should return filename with the name that the Google give.

Sorry, but am'I wrong?

**Comment by angeljqv** [comment]
> Sorry, but am'I wrong?

Big yes, laravel handles only display paths, that means it return original filename, check laravel sources
>this package works independently of Laravel

and `useDisplayPaths = false` is only for emulate old https://github.com/nao-pon/flysystem-google-drive package

If you feel it should work the way you want feel free to open a PR with your changes.
