### ISSUE TITLE
On live Server, google drive backup is giving error!

### ISSUE THREAD

**Issue by PrantoPodder98** [masbug/flysystem-google-drive-ext#129]
Google drive backup is perfectly working on local server. But  when I host this on live Server(cpanel). It's giving this error:
"Exception message: Unable to write file at location: project/2024-06-24-17-35-33.zip. Not able to write the file."

how to solve this?

**Comment by parallels999** [comment]
[Not able to write the file](https://www.google.com/search?q=linux+Exception+message%3A+Unable+to+write+file+at+location+Not+able+to+write+the+file.&oq=linux+Exception+message%3A+Unable+to+write+file+at+location+Not+able+to+write+the+file)

**Comment by masbug** [comment]
I assume this has been solved.

**Comment by PrantoPodder98** [comment]
Yes the problem is solved, thanks for the reply.
