### ISSUE TITLE
Unable to upload file (production)

### ISSUE THREAD

**Issue by kevinpallado** [masbug/flysystem-google-drive-ext#131]
Production Server Specs - I am currently using forge in deploying my apps so the setup is base on forge

- Ubuntu 24
- Nginx
- Php 8.2
- Laravel 10.10

Local Host Server
- Windows 10
- Laragon

I am using this library for uploading files to google drive it works for several months but then now something went wrong. I guess this affects the new updates of google drive API but I am not sure where. But locally server hosted in windows I can upload using the code provided below

Code used in uploading file
```
$fileName = formatFileName($fileUpload->getClientOriginalName());
Storage::disk('google')->put('Sample Directory/'.$fileName, fopen($fileUpload,'r+'));
```

Here is a snippet of how the uploaded files metadata when the 2nd line of code is executed

Production Setup
![image](https://github.com/user-attachments/assets/2079694a-cd73-46a9-af52-e390007cbc30)

Local Setup
![image](https://github.com/user-attachments/assets/ebbd43c9-6df4-4009-b548-0d981f1cc9dc)

**Comment by masbug** [comment]
By google drive API I assume you mean "google/apiclient" library. Look at the composer.lock file and determine if windows version is different than the one on linux. If so, then just downgrade/upgrade it on linux and test.

I would also test that fopen actually works for the file (various permission issues).

**Comment by kevinpallado** [comment]
@masbug tested it out download grade necessary packages below, still got same error. You can also use putFileAs and still you get the same error

"league/flysystem-local": "3.28.0"
league/flysystem => 3.28.0
google/apiclient => 2.16.0
google/apiclient-services => 0.362.0
google/auth => 1.40.0

**Comment by kevinpallado** [comment]
@masbug Another thing to note, last time I fix this one by setting permissions to tmp folders, change the SELINUX config and it works but now it goes back again

**Comment by masbug** [comment]
Try setting the storage config setting ```'throw' => true```  to see where the error is coming from.

**Comment by masbug** [comment]
> @masbug Another thing to note, last time I fix this one by setting permissions to tmp folders, change the SELINUX config and it works but now it goes back again

Permission issues do not stem from this library. Look into setting your own temp folder instead of using a system one.

**Comment by kevinpallado** [comment]
@masbug the problem here is that I cannot see what is the actual problem as I only know that uploading has a problem is when my system tries to sync data to google drive which I found out that no files has been uploaded to drive. As I investigated further

this line of code `Storage::disk('google')->put('Sample Directory/'.$fileName, fopen($fileUpload,'r+'));` supposed to be return a string of path but turns out returns false

Setting  `'throw' => true` on filesystem has no useful info that I can figure out why it no false is detected
