### ISSUE TITLE
FileNotFoundException with sanitize_chars in directory name

### ISSUE THREAD

**Issue by martinwang2002** [masbug/flysystem-google-drive-ext#18]
FileNotFoundException will raise if `sanitize_chars` exist in directory name

Sample path to reproduce
```
$remote_filepath = '[test]test/test.txt';
```
I have passed `sanitize_chars` without `[` and `]` in `options` of `Masbug\Flysystem\GoogleDriveAdapter`, but doesn't help.

<details>
  <summary>Logs</summary>
   League\Flysystem\FileNotFoundException 

  File not found at path: [test]test

  at \vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php:1773
    1769▕         if($makeFullVirtualPath)
    1770▕             return $this->makeFullVirtualPath($displayPath, $returnFirstItem);
    1771▕
    1772▕         if(empty($this->cachedPaths[$displayPath]))
  ➜ 1773▕             throw new FileNotFoundException($displayPath);
    1774▕
    1775▕         return $this->returnSingle($this->cachedPaths[$displayPath], $returnFirstItem);
    1776▕     }
    1777▕

  1   \vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php:1824
      Masbug\Flysystem\GoogleDriveAdapter::toVirtualPath("[test]test")

  2   \vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php:297
      Masbug\Flysystem\GoogleDriveAdapter::toSingleVirtualPath("[test]test")

</details>

**Comment by erikn69** [comment]
@martinwang2002 Did you try the last unreleased changes on flysystem-google-drive-ext 1.x, 
i believe that bug is already fixed by me
https://github.com/masbug/flysystem-google-drive-ext/blob/198be5273aee29072b63205c63299a36e3307394/tests/GoogleDriveAdapterTests.php#L416-L440
Give a try please, @masbug if works on this test, maybe he needs a new release, also there is'nt v2's release

**Comment by erikn69** [comment]
I run '[test]test/test.txt' on testing
```php
public function testWritingReadingFilesWithSpecialPath()
    {
        $adapter = $this->adapter();
        foreach ([
            'a path with square brackets in dirname 2' => '[test]test/test.txt',
        ] as $msg => $path) {
            $adapter->write($path, 'contents', new Config());
            $contents = $adapter->read($path);

            $this->assertEquals('contents', isset($contents['contents']) ? $contents['contents'] : '', $msg);
        }
 }
```
I get 
```
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.5
Configuration: google_flysystem\phpunit.xml.dist

.                                                                   1 / 1 (100%)

Time: 00:05.495, Memory: 8.00 MB

OK (1 test, 1 assertion)
```
![image](https://user-images.githubusercontent.com/4933954/123476284-1c4b4a00-d5c2-11eb-8444-9a34e9486ce1.png)

**Comment by martinwang2002** [comment]
Great! I have tested and it works. I got this package via packagist, so a new version is preferred.

**Comment by erikn69** [comment]
@masbug I have fixed some common bugs, and i made it works as expected behavior according v1 and v2 flysystem docs, so, when would the new release date be?

**Comment by masbug** [comment]
@erikn69 Sorry for my tardiness. Thank you for the great work you've done so far! I tagged the releases for both branches.
