### ISSUE TITLE
travis-ci.org deprecated, should be replaced with travis-ci.com

### ISSUE THREAD

**Issue by erikn69** [masbug/flysystem-google-drive-ext#24]
Hello, watching a [build](https://travis-ci.org/github/masbug/flysystem-google-drive-ext/builds/772631824) on Travis I noticed this alert:

>Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

Please update the project configuration.

**Comment by masbug** [comment]
It seems travis-ci.com <-> github integration is broken at the moment... I select the repo, allow everything and then I get "We couldn’t find any active repositories you have access to." on travis-ci.com. I guess we have to wait a bit longer :)

**Comment by masbug** [comment]
Fixed.
