### ISSUE TITLE
Access to Google_Service_Drive property

### ISSUE THREAD

**Issue by unsa-cdn** [masbug/flysystem-google-drive-ext#27]
Hi I really need this property to have a getter as in nao-pon/flysystem-google-drive `getService()`
https://github.com/masbug/flysystem-google-drive-ext/blob/1572b60e44cb98b18d54e1ad440547a2cb6fc0ef/src/GoogleDriveAdapter.php#L62
Case scenario is when I need to put custom permissions on drive objects.

**Comment by masbug** [comment]
But why? You create the adapter by passing the $service in the constructor.

In the other issue you mentioned storing ids instead of display paths. I think nao-pon's variant is a better fit for you as this adapter is specifically focused on hiding "virtual paths" (paths made of ids) and useDisplayPaths==false is only meant for debugging and further development.

**Comment by erikn69** [comment]
`$service = new \Google_Service_Drive($client);`

![image](https://user-images.githubusercontent.com/4933954/125634722-5b59e3c0-40ca-402b-89b2-c4d86a6d3e73.png)

>Case scenario is when I need to put custom permissions on drive objects.

Maybe on constructor you can set your custom permissions  with `publishPermission` propertie on `$options`
https://github.com/masbug/flysystem-google-drive-ext/blob/aaa3b0af75b4262b63c37f3840960d89dab0797b/src/GoogleDriveAdapter.php#L222
```php
[
   'publishPermission' => [
            'type'     => 'anyone',
            'role'     => 'reader',
            'withLink' => true
    ]
]
```
And then use `public function setVisibility($path, $visibility)`  for set and unset
```php
$adapter->setVisibility('path/to/file.txt',AdapterInterface::VISIBILITY_PUBLIC); //set permission
$adapter->setVisibility('path/to/file.txt',AdapterInterface::VISIBILITY_PRIVATE); //unset permission

```
`public function getVisibility($path)` returns permission
```php
$permission=$adapter->getVisibility('path/to/file.txt');
// $permission results
//[
//    'visibility' => AdapterInterface::VISIBILITY_PRIVATE
//]
```

**Comment by erikn69** [comment]
@masbug `getService()` maybe can be usefull for `emptyTrash`, or permanently `delete` like [#28](https://github.com/masbug/flysystem-google-drive-ext/issues/28), 
or for reuse it(laravel for example, `Storage::disk('google')->getDriver()->getAdapter()`, we can't get `protected $service;` here).

**Comment by unsa-cdn** [comment]
@masbug Indeed nao-pon's variant is better fit for me but that repo is no loger receiving updates. If you think this issue will cause that trouble then no problem I will make a fork.
@erikn69 Thanks for your advice but public and private visibility are not the only cases I need for permissions. I need finer controll over them. What if I want different roles for different types?

**Comment by erikn69** [comment]
@unsa-cdn this package is a **Flysystem adapter**, so according to the documentation only handles `VISIBILITY_PUBLIC ` and `VISIBILITY_PRIVATE `
https://github.com/thephpleague/flysystem/blob/f3ad69181b8afed2c9edf7be5a2918144ff4ea32/src/AdapterInterface.php#L7-L15
maybe you can make a PR, or maybe it's more useful avoid **Flysystem** and only use `$service = new \Google_Service_Drive($client);`

**Comment by erikn69** [comment]
@unsa-cdn Added `getService()`, issue must be closed
