### ISSUE TITLE
Delete forever ?

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#28]
When i use `Storage::disk('google')->delete($file)` it move the file into trash section, how can i delete file forever ?

**Comment by erikn69** [comment]
files in trash section are deleted forever after a month
>Items in the trash will be permanently deleted after 30 days

**Comment by foremtehan** [comment]
@erikn69 the issue is the storage become full before a month my db is large

**Comment by erikn69** [comment]
Also you can do it manually
![image](https://user-images.githubusercontent.com/4933954/125642555-4d83ecee-0474-417f-9a6e-26c04412c4f7.png)

So, after your `backup:clean`
```php
$service = new \Google_Service_Drive($client); //from basic usage
$service->files->delete($id_de_google, []); //delete permanently but needs $id of google, not path
$service->files->emptyTrash([]); // delete all files on trash permanently 
```

**Comment by masbug** [comment]
@foremtehan I merged the fixes that Erik implemented for you.
@erikn69 I think it might be useful to add a config param that would toggle weather or not to add files to trash folder ($file->setTrashed(true)) or just plain delete them.

**Comment by erikn69** [comment]
@foremtehan permanent delete on config
