### ISSUE TITLE
I can't install this package in laravel 8

### ISSUE THREAD

**Issue by CristhoferMF** [masbug/flysystem-google-drive-ext#37]
Problem 1
    - Conclusion: don't install masbug/flysystem-google-drive-ext v2.0.0 (conflict analysis result)
    - Root composer.json requires masbug/flysystem-google-drive-ext ^2.0 -> satisfiable by masbug/flysystem-google-drive-ext[v2.0.0, 2.x-dev].
    - Conclusion: don't install league/flysystem 1.1.2 (conflict analysis result)
    - Conclusion: don't install league/flysystem 2.2.0 (conflict analysis result)
    - Conclusion: don't install league/flysystem 1.1.3 (conflict analysis result)
    - Conclusion: don't install league/flysystem 2.2.1 (conflict analysis result)
    - Conclusion: don't install league/flysystem 1.1.4 (conflict analysis result)
    - Conclusion: don't install league/flysystem 2.2.2 (conflict analysis result)
    - Conclusion: don't install league/flysystem 1.1.5 (conflict analysis result)
    - Conclusion: don't install league/flysystem 2.2.3 (conflict analysis result)
    - laravel/framework is locked to version v8.54.0 and an update of this package was not requested.
    - laravel/framework v8.54.0 requires league/flysystem ^1.1 -> satisfiable by league/flysystem[1.1.0, ..., 1.x-dev].
    - You can only install one version of a package, so only one of these can be installed: league/flysystem[1.1.0, ..., 1.x-dev, 2.1.1, ..., 2.x-dev].
    - masbug/flysystem-google-drive-ext 2.x-dev requires league/flysystem ^2.1.1 -> satisfiable by league/flysystem[2.1.1, ..., 2.x-dev].
    - Conclusion: don't install league/flysystem 2.1.1 (conflict analysis result)

**Comment by masbug** [comment]
masbug/flysystem-google-drive-ext 2.0+ is compatible with league/flysystem 2.0+...for 1.0+ use masbug/flysystem-google-drive-ext ^1.0

**Comment by erikn69** [comment]
you may have to add a note to avoid this confusion in the future
