### ISSUE TITLE
GoogleDriveAdapter FileNotFoundException

### ISSUE THREAD

**Issue by brencaivan** [masbug/flysystem-google-drive-ext#56]
I'm having an error while using Storage::disk('google')->getDriver()->getAdapter()->getMetadata("sample.png"). It says file is not found at \\/(_virtual filename here_). It always prepend "\\/" which I think causes the error. But when I use Storage::disk('google')->getFiles(), it successfully displays all the files in the google drive folder so I'm pretty sure it can access the folder. What can be the problem in my case?

**Comment by masbug** [comment]
Not sure. Which branch are you using and on which platform? I am unable to reproduce this with version 1.2.5 on linux (can't test with V2 branch atm).

**Comment by brencaivan** [comment]
I'm using V1 on a Laravel app. By the way, I just found out the problem in my case. Util::dirname() in getMetadata() prepends a "\\" to the $path. So I just removed it and everything's alright now. :)

**Comment by masbug** [comment]
You mean self::dirname aka. GoogleDriveAdapter::dirname or Util::normalizeDirname? Because I don't see any prepending in the code.

**Comment by erikn69** [comment]
Weird, `getMetadata` is on test

https://github.com/masbug/flysystem-google-drive-ext/blob/81afc0d2c5eec5ef1b95163e2d1cfceb7b25f3ff/tests/GoogleDriveAdapterTests.php#L338

maybe you are adding `"\/"` on creation
```php
new \Masbug\Flysystem\GoogleDriveAdapter($service, '\/', $options);
```

**Comment by masbug** [comment]
Closing due to no response from brencaivan.
