### ISSUE TITLE
Unable to run backup spatie/laravel-backup

### ISSUE THREAD

**Issue by paramwork** [masbug/flysystem-google-drive-ext#59]
I am using Laravel 9. I can use Storage to put file into Google Drive but when I run artisan backup:run it throws expection.

`Copying zip failed because: Could not connect to disk google because: League\Flysystem\UnableToReadFile: Unable to read file from location: launchlist. File not found 
in E:\dev\code\getlaunchlist\vendor\league\flysystem\src\UnableToReadFile.php:24
Stack trace:
#0 E:\dev\code\getlaunchlist\vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php(1869): League\Flysystem\UnableToReadFile::fromLocation('launchlist', 'File not found')
#1 E:\dev\code\getlaunchlist\vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php(1967): Masbug\Flysystem\GoogleDriveAdapter->makeFullVirtualPath('launchlist', false)
#2 E:\dev\code\getlaunchlist\vendor\masbug\flysystem-google-drive-ext\src\GoogleDriveAdapter.php(805): Masbug\Flysystem\GoogleDriveAdapter->toVirtualPath('launchlist')#3 E:\dev\code\getlaunchlist\vendor\league\flysystem\src\DirectoryListing.php(33): Masbug\Flysystem\GoogleDriveAdapter->listContents('launchlist', true)
#4 E:\dev\code\getlaunchlist\vendor\league\flysystem\src\DirectoryListing.php(46): League\Flysystem\DirectoryListing::League\Flysystem\{closure}(Object(Generator))    
#5 [internal function]: League\Flysystem\DirectoryListing::League\Flysystem\{closure}(Object(Generator))
#6 E:\dev\code\getlaunchlist\vendor\league\flysystem\src\DirectoryListing.php(81): iterator_to_array(Object(Generator), false)
#7 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(728): League\Flysystem\DirectoryListing->toArray()
#8 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(739): Illuminate\Filesystem\FilesystemAdapter->files('launchlist', true)
#9 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\BackupDestination\BackupDestination.php(140): Illuminate\Filesystem\FilesystemAdapter->allFiles('launchlist')
#10 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(286): Spatie\Backup\BackupDestination\BackupDestination->isReachable()       
#11 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Collections\Traits\EnumeratesValues.php(263): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#12 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(304): Illuminate\Support\Collection->each(Object(Closure))
#13 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\Tasks\Backup\BackupJob.php(168): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('E:\\dev\\code\\get...')
#14 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\Commands\BackupCommand.php(58): Spatie\Backup\Tasks\Backup\BackupJob->run()
#15 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Spatie\Backup\Commands\BackupCommand->handle()
#16 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Container\Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()       
#17 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))       
#18 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#19 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Container\Container.php(653): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#20 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Console\Command.php(136): Illuminate\Container\Container->call(Array)
#21 E:\dev\code\getlaunchlist\vendor\symfony\console\Command\Command.php(291): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#22 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Console\Command.php(121): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#23 E:\dev\code\getlaunchlist\vendor\spatie\laravel-backup\src\Commands\BaseCommand.php(28): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 E:\dev\code\getlaunchlist\vendor\symfony\console\Application.php(989): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 E:\dev\code\getlaunchlist\vendor\symfony\console\Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(Spatie\Backup\Commands\BackupCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 E:\dev\code\getlaunchlist\vendor\symfony\console\Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Console\Application.php(102): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 E:\dev\code\getlaunchlist\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(129): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#29 E:\dev\code\getlaunchlist\artisan(37): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 {main}.`

Please help me fix this issue

**Comment by erikn69** [comment]
I'm using laravel backup without problems #26

**Comment by paramwork** [comment]
> I'm using laravel backup without problems

@erikn69 I know many this plugin is compatible with laravel backup. But I am missing something that I can't seems to figure. 

Do you think it is a Windows problem or with my files directories as error is " Unable to read file from location: launchlist. File not found in" ?

Backup is running without any issues on S3 and local btw.

**Comment by erikn69** [comment]
>This backup package requires PHP 8.0, with the [ZIP module](http://php.net/manual/en/book.zip.php) and Laravel 9.0 or higher. It's not compatible with Windows servers.

It not has support for windows, [requirements](https://spatie.be/docs/laravel-backup/v8/requirements#breadcrumb)

But if you find a bug, make a PR

**Comment by paramwork** [comment]
> > This backup package requires PHP 8.0, with the [ZIP module](http://php.net/manual/en/book.zip.php) and Laravel 9.0 or higher. It's not compatible with Windows servers.
> 
> It not has support for windows, [requirements](https://spatie.be/docs/laravel-backup/v8/requirements#breadcrumb)
> 
> But if you find a bug, make a PR

I mean I am not using windows on server. My server is linux ami. I am developing locally on windows where "local" and "s3" is working fine. There is some issue with plugin.

**Comment by erikn69** [comment]
It is impossible for me to replicate your problem because everything is working correctly on my side #26, if you see the problem, do a test that demonstrates the problem on a laravel minimal aplication, so that others can review it, or do a pull request with the solution

**Comment by erikn69** [comment]
Tested on windows 10 with laravel 9 and mysql, everyting working as expected

**Comment by paramwork** [comment]
Okay sure.

**Comment by nocodelab** [comment]
You can fix it adding this in backup.php from spatie backup package:

`        'name' => preg_replace('/[^a-zA-Z0-9._]/', '-', env('APP_NAME', 'laravel-backup')),`

It's a problem related to the underscores added by that package.
