### ISSUE TITLE
Example of path abstraction?

### ISSUE THREAD

**Issue by Artusamak** [masbug/flysystem-google-drive-ext#6]
Hi there!

Thank you for this bundle, it's very interesting and promising!

I've tested it, successfully uploaded a doc to a specific parent folder but i have to use hashes and only one hash. If i try to have a folder structure `folder_name/subfolder/file.txt` Google SDK throws an exception `File not found: folder_name`. I suspected a shared folder as root to be the source of the issue but even if i try with a non-shared folder i have the same error.

I also tried to use IDs instead of "path abstractions" (eg: 12ESDFS/93JKDLDFK/file.txt) but it throws the same error.

Would it be possible to have an example to manage the folders path abstraction or direct file upload in a subfolder please? I'm sad to miss the fun of the package if this doesn't work.

Thank you very much for your time! :pray:

**Comment by masbug** [comment]
Hi,

I'm not sure I follow. The root folder ID should be automatically determined by the adapter. You should never need to use the IDs. That is the purpose of this driver.

Under the "Usage" chapter you have a few examples. Even the direct file upload to a subfolder.
These are not working for you?

**Comment by Artusamak** [comment]
Got it! I found what was wrong, i was following your documentation but had used the composer require of another package i tested.

Problem solved, thank you for your help!
