### ISSUE TITLE
Error: "Properties can not be manipulated"

### ISSUE THREAD

**Issue by achatzi78** [masbug/flysystem-google-drive-ext#60]
Hello.

I have a fresh installation of Laravel 9 with php 8.1.2 and I added your package according to your instructions.

When I try to access my Google drive I get this error "Properties can not be manipulated".

Following the breadcrumbs, the problem starts in the file `Masbug\Flysystem\GoogleDriveAdapter` in the function `setHasDir`
```php
foreach ($results as $key => $result) {
            if ($result instanceof FileList) {
                $object[$paths[$key]]['hasdir'] = $this->cacheHasDirs[$paths[$key]] = (bool)$result->getFiles();//this is the problem
            }
        }
```
which uses the function `offsetSet` in the file `League\Flysystem\DirectoryAttributes` which uses the trait `ProxyArrayAccessToProperties` which contains this function.

In this trait the functions offsetSet and offsetUnset throw this exception directly
```php
/**
     * @param mixed $offset
     * @param mixed $value
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value): void
    {
        throw new RuntimeException('Properties can not be manipulated');
    }

    /**
     * @param mixed $offset
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset): void
    {
        throw new RuntimeException('Properties can not be manipulated');
    }
```

If I comment the throw part (I know I am not supposed to), everything seems fine (emphasis on the seems).

Do you have any idea what this issue is about?  Has anyone else encountered this?

Thanks.

**Comment by erikn69** [comment]
I tested on a fresh instalation(Laravel v9.8.1 and PHP 8.1.2) and i am unable to replicate the exception
https://github.com/erikn69/laravel-google-drive-ext-demo
https://github.com/erikn69/laravel-google-drive-ext-demo/blob/80cc69fbb3989c24387b941c8841e249033ffc21/routes/web.php#L32-L40

Also you can run the tests
https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/tests/GoogleDriveAdapterTests.php

**Comment by masbug** [comment]
@achatzi78 Have you found the cause? If not, then can you show a minimal example that reproduces your issue?

**Comment by achatzi78** [comment]
@erikn69 @masbug  At first I had an older app, with Laravel 8 and php7, which I upgraded to Laravel 9 and php8.1 and I got this error.  Then, I tried with another app that is currently under development with Laravel 9 and php 8.1 in case something in the upgrade went wrong.  I still got the same error.  Then, after your comment, I tried with a fresh installation of Laravel and everything works.  Maybe something in the versions is messed up or another package is interefering with this package?

In any case, this is what I use

This is my service provider

```php
namespace App\Providers;

use Google\Client as GoogleClient;
use Google\Service\Drive as GoogleServiceDrive;
use Illuminate\Filesystem\FilesystemAdapter;
use Illuminate\Support\ServiceProvider;
use League\Flysystem\Filesystem;
use Masbug\Flysystem\GoogleDriveAdapter;
use Storage;

class GoogleDriveServiceProvider extends ServiceProvider
{
    /**
     * Register services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap services.
     *
     * @return void
     */
    public function boot()
    {
        Storage::extend('google', function($app, $config) {
            $client = new GoogleClient();
            $client->setClientId($config['clientId']);
            $client->setClientSecret($config['clientSecret']);
            $client->refreshToken($config['refreshToken']);

            $service = new GoogleServiceDrive($client);
            $adapter = new GoogleDriveAdapter($service, $config['folderName'], [
                'useHasDir' => true,
            ]);
            $driver = new Filesystem($adapter);

            return new FilesystemAdapter($driver, $adapter);
        });
    }
}
```

In the filesystems config file I have
```php
'cloud' => env('FILESYSTEM_CLOUD', 'google'),
...
'google' => [
            'driver' => 'google',
            'clientId' => env('GOOGLE_DRIVE_CLIENT_ID', '),
            'clientSecret' => env('GOOGLE_DRIVE_CLIENT_SECRET', ''),
            'refreshToken' => env('GOOGLE_DRIVE_REFRESH_TOKEN', ''),
            'folderId' => env('GOOGLE_DRIVE_FOLDER_ID', ''),
            'folderName' => env('GOOGLE_DRIVE_FOLDER_NAME', 'Websites/LiferaftsApp'),
            'sheetId' => env('GOOGLE_DRIVE_PATH_MANAGER_SHEET_ID'),
            'visibility' => 'private',
        ],
```

When I use `Storage::cloud()->get('somefile.txt')` I get this exception.  I have also attached the composer.json and composer.lock files in case you can find something useful there.  Let me know if you need anything more.
[composer.lock.txt](https://github.com/masbug/flysystem-google-drive-ext/files/8513175/composer.lock.txt)
[composer.json.txt](https://github.com/masbug/flysystem-google-drive-ext/files/8513176/composer.json.txt)
.

**Comment by erikn69** [comment]
Ok, I know your error, on laravel 9 filesystem declaration has a breaking change, read laravel upgrade or look at the demo that I let you

**Comment by erikn69** [comment]
@achatzi78 test #66

**Comment by achatzi78** [comment]
@erikn69 Your fix works.  For now I have made the change in the vendor directory of my projects, until this is included in a new release.

Thanks everybody for your help.
