### ISSUE TITLE
Unable to retrieve the file_size Error

### ISSUE THREAD

**Issue by hckoks** [masbug/flysystem-google-drive-ext#68]
Hello I got this issue 
League\Flysystem\UnableToRetrieveMetadata 

 Unable to retrieve the file_size for file at location: 2022-05-26-15-00-03.zip.

**Comment by hckoks** [comment]
Any update on this issue ?

**Comment by hckoks** [comment]
The backups on google are considered unhealthy!

   League\Flysystem\UnableToRetrieveMetadata 

  Unable to retrieve the file_size for file at location: 2022-05-31-09-00-03.zip.

  at vendor/league/flysystem/src/UnableToRetrieveMetadata.php:49
     45▕     }
     46▕ 
     47▕     public static function create(string $location, string $type, string $reason = '', Throwable $previous = null): self
     48▕     {
  ➜  49▕         $e = new static("Unable to retrieve the $type for file at location: $location. {$reason}", 0, $previous);
     50▕         $e->reason = $reason;
     51▕         $e->location = $location;
     52▕         $e->metadataType = $type;
     53▕ 

      +45 vendor frames 
  46  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

This is what i get

**Comment by erikn69** [comment]
> Any update on this issue ?

Not, because you did give almost no information

Package version? laravel version? php version? what are you trying to do? steps to reproduce the exception or a failing test?

**try the previous version**, maybe it works

**Comment by hckoks** [comment]
Actually I am using 
Laravel  : 9.*
PHP : 8.0
Package version : 2.2.1

**Comment by hckoks** [comment]
Actually v2.2.0 works perfectly but there is issue in v2.2.1

**Comment by oriceon** [comment]
I also confirm this issue in 2.2.1.

**Comment by kitro** [comment]
I also confirm the same issue in v2.2.1. 
v2.2.0 works well.

**Comment by fredsal** [comment]
>Any update on this issue ?

No, because you and @oriceon didn't give this package a star.

**Comment by erikn69** [comment]
Sorry, I have not had time, nor managed to replicate the problem
Try this change
```php
-$query = $is_last ? [] : ['mimeType = "'.self::DIRMIME.'"'];
-$query[] = "name = '{$token}'";
+$query = $is_last ? ["name = '{$token}'"] : ['mimeType = "'.self::DIRMIME.'"'];
```
