### ISSUE TITLE
Unsupported characters

### ISSUE THREAD

**Issue by dfuse-dev** [masbug/flysystem-google-drive-ext#69]
Hi,

Thank you for this one it looks amazing while im trying.

Ive noticed that i cant use character '#' nor ':' in folder/file name. Are there other characters that wont work?

For instance:

$remote_filepath = '[ID #4382] USERNAME: Blah Blah Blag/file.txt'; // this wont work
$remote_filepath = '[ID 4382] USERNAME - Blah Blah Blag/file.txt'; // this will work

Thanks again

**Comment by erikn69** [comment]
Not a bug, you can change that with the configs
https://github.com/masbug/flysystem-google-drive-ext/blob/c9dc6cd959d1d4c45f3cd5afcf63341d5098fa16/src/GoogleDriveAdapter.php#L108

**Comment by dfuse-dev** [comment]
Thanks
