### ISSUE TITLE
directoryExists not defined

### ISSUE THREAD

**Issue by dfuse-dev** [masbug/flysystem-google-drive-ext#70]
Hi,

Tried to check if folder exists to prevent multiple folders with the same name: 

```
if(!$fs->directoryExists($directory))
       $fs->createDirectory($directory, ['visibility' => 'private']);
```
but it throws an error. Am I trying something wrong? Tried with fileExists but doesnt work for directories.

undefined method League\Flysystem\Filesystem::directoryExists()

Thanks again!

**Comment by erikn69** [comment]
I dont remember, but I think, that method was deleted on laravel 9

**Comment by dfuse-dev** [comment]
Thanks @erikn69 

Ive realized that i was calling method from $fs istead of from $adapter->directoryExists where it is implemented. By the way im trying to check multiple folders exist and results are a bit weird because knowing that all of them exist it returns false every odd one... first is true, second is false, third is true, fourth is false... (tried to put a sleep(5) between loops with the same result):

Note that im working in a teamdrive

```
$remoteDirectory = [
    $lowestYear.'/'.$mainDirName.'/01-Op',
    $lowestYear.'/'.$mainDirName.'/02-Or',
    $lowestYear.'/'.$mainDirName.'/03-Pl',
    $lowestYear.'/'.$mainDirName.'/04-As',
    $lowestYear.'/'.$mainDirName.'/05-Sc',
    $lowestYear.'/'.$mainDirName.'/06-Re',
    $lowestYear.'/'.$mainDirName.'/07-In',
    $lowestYear.'/'.$mainDirName.'/08-It',
];
foreach($remoteDirectory as $directory) {
    $dirExists = $adapter->directoryExists($directory);
    echo $directory."<pre>".print_r($dirExists, true)."</pre>";
    if(!$dirExists) {
        try {
            $fs->createDirectory($directory, ['visibility' => 'private']);
        } catch(\League\Flysystem\UnableToCreateDirectory $e) {
            echo 'Unable to create dir!!'.PHP_EOL.$e->getMessage();
        }
    }
}
```

Thanks again

**Comment by erikn69** [comment]
Maybe related https://github.com/masbug/flysystem-google-drive-ext/issues/67
