### ISSUE TITLE
Login Required

### ISSUE THREAD

**Issue by juicyfish** [masbug/flysystem-google-drive-ext#71]
I am getting the following error:

```
{ "error": { "errors": [ { "domain": "global", "reason": "required", "message": "Login Required", "locationType": "header", "location": "Authorization" } ], "code": 401, "message": "Login Required" } }
```

I have used the `clientId`, `clientSecret` and `refreshToken` in the Google Playground successfully. I have Googled and found others having a similar issue with a similar package, but no real fixes.

I'm using:

`"laravel/framework": "^v9.17.0",`
`"masbug/flysystem-google-drive-ext": "^v2.2.1"`

Any help much appreciated.
Roger

**Comment by erikn69** [comment]
Just read the documentation again, you missed a step
If you did already working, and it stops after days, you are on test mode application

**Comment by juicyfish** [comment]
Thanks for the quick reply.  I went through the docs again and recreated the project with a new Google Cloud Platform project with the same results. I guess I'm still missing something!

**Comment by jw7712** [comment]
Hello,
I have the same error, it works for about 5 days and then I get a 401 error: Login required.
@erikn69 mentioned 
> "If you did already working, and it stops after days, you are on test mode application"

This could be the case, how can i change the mode so that it is not in test mode anymore?
Thanks in advance

**Comment by erikn69** [comment]
> how can i change the mode so that it is not in test mode anymore?

You have to look on google

![image](https://user-images.githubusercontent.com/4933954/178341163-b6cb1e40-cc39-4ec2-bda8-a50416366d2b.png)
https://developers.google.com/identity/protocols/oauth2#expiration
>A Google Cloud Platform project with an OAuth consent screen configured for an external user type and a publishing status of "Testing" is issued a refresh token expiring in 7 days.
>
>There is currently a limit of 50 refresh tokens per Google Account per OAuth 2.0 client ID. If the limit is reached, creating a new refresh token automatically invalidates the oldest refresh token without warning.

**Comment by jw7712** [comment]
@erikn69 
Thanks for the quick reply. 
I found the option from your screenshot in the "oauth consent page".
I thought i needed to go through the verification process to activate the production option, but it seems this it not mandatory?
I assume that it will work now, thanks a lot for your quick reply!

**Comment by erikn69** [comment]
>Thanks for the quick reply.

Just give a start on signal of support
