### ISSUE TITLE
Get infomration about uploaded file when using Laravel

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#72]
When uploading some file with Laravel like so:

```php
Storage::disk('google')->writeStream('composer.json', fopen('composer.json', 'r')) // true
```

The output of `writeStream` is boolean, Is there another method that get more information about uploaded file ?

like file_id, created_at etc ... ?

masbug/flysystem-google-drive-ext: 2.1
laravel 9

**Comment by erikn69** [comment]
getAdapter getMetatada

**Comment by foremtehan** [comment]
So it should be 2 requests right ?

```php
$path = 'composer.json';

Storage::disk('google')->writeStream('composer.json', fopen($path, 'r'));

Storage::disk('google')->getAdapter()->getMetadata($path); 
```

The `upload` can return the metadata directly and in one request, But unfortunately it's not public method:

https://github.com/masbug/flysystem-google-drive-ext/blob/c9dc6cd959d1d4c45f3cd5afcf63341d5098fa16/src/GoogleDriveAdapter.php#L1385

**Comment by oxytoxin** [comment]
did you somehow find a workaround for this? I also needed the id and would prefer it in one request.

**Comment by foremtehan** [comment]
No
