### ISSUE TITLE
File download using file's id

### ISSUE THREAD

**Issue by foremtehan** [masbug/flysystem-google-drive-ext#80]
masbug/flysystem-google-drive-ext: 2.1
laravel 9

I save the file's id in my table instead of path, So how can download them ? I try the following but it return null instead of stream resource:

```php
$resource = Storage::disk('google')->readStream('1_g53alfVsT-90wwLDwSqD7E_9EZ5wev69Ty'); // this is null

Storage::writeStream('file.pdf', $resource)
```

```
League\Flysystem\InvalidStreamProvided : Invalid stream provided, expected stream resource, received NULL
```

**Comment by erikn69** [comment]
Read documentantion, this package uses paths

**Comment by foremtehan** [comment]
Ok, Is there a way to translate id to path ?

**Comment by erikn69** [comment]
I don't know, I think it's possible, but it needs work
but what I know is that this is not a bug, use the _**discussions**_ section for this type of posts

**Comment by erikn69** [comment]
Maybe ` 'useDisplayPaths'   => false, `
https://github.com/masbug/flysystem-google-drive-ext/blob/3947d39be212bff9cea95b2a5252e52c9eb36cc0/src/GoogleDriveAdapter.php#L88

**Comment by foremtehan** [comment]
Yeah that worked, thanks man
