### ISSUE TITLE
Upload of images to Google Drive is killing my bandwidth/freezes my site

### ISSUE THREAD

**Issue by Arturexe** [masbug/flysystem-google-drive-ext#81]
When executing this line of code:
```
Storage::disk('google')->put($imageId, base64_decode($src));
```

my whole app becomes unresponsive. When opening a new browser tab, the page doesn't load before the upload to drive is finished. I assume that the upload to drive burns up my whole `upload bandwidth`. Is there a throttle option or another way to prevent this from happening?

I'm using `drive` to store and retrieve images.

Here's my `GoogleDriveServiceProvider.php`:
```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Storage;
use Google\Client;
use Google\Service\Drive;
use Masbug\Flysystem\GoogleDriveAdapter;
use League\Flysystem\Filesystem;
use Illuminate\Filesystem\FilesystemAdapter;


class GoogleDriveServiceProvider extends ServiceProvider
{

    public function register()
    {
        //
    }

    public function boot()
    {
        try {
            Storage::extend('google', function($app, $config) {
                $options = [];

                if (!empty($config['teamDriveId'] ?? null)) {
                    $options['teamDriveId'] = $config['teamDriveId'];
                }

                $client = new Client();
                $client->setClientId($config['clientId']);
                $client->setClientSecret($config['clientSecret']);
                $client->refreshToken($config['refreshToken']);

                $service = new Drive($client);
                
                $adapter = new GoogleDriveAdapter($service, $config['folder'] ?? '/', $options);
                $driver = new Filesystem($adapter);

                return new FilesystemAdapter($driver, $adapter);
            });
        } catch(\Exception $e) {
            return $e->getMessage();
        }
    }
}
```

**Comment by erikn69** [comment]
Maybe try this https://github.com/masbug/flysystem-google-drive-ext/commit/8afb3ff6a839f52f7255e10506586f6b108dccf2

**Comment by masbug** [comment]
@Arturexe 
First of all, all of the below is out of scope of "issues" section.

>> When opening a new browser tab, the page doesn't load before the upload to drive is finished.

This is normal. The whole operation is synchronous. If you want to make it async then you need to create a worker and send the upload job to it.

>>  I assume that the upload to drive burns up my whole upload bandwidth. Is there a throttle option or another way to prevent this from happening?

Of course it does. It performs a series of web requests.
You could try to set global "curl" settings and try to throttle the bandwidth that way. Hint: https://curl.se/libcurl/c/CURLOPT_MAX_RECV_SPEED_LARGE.html
