### ISSUE TITLE
getting display path with `useDisplayPath` set to `false`

### ISSUE THREAD

**Issue by jacekkarczmarczyk** [masbug/flysystem-google-drive-ext#84]
I'm using folder/file's ID to set the root dir, list the folder contents, get files' contents etc etc. It seems that it requires setting `useDisplayPaths` to `false` but when I set this I'm not able to retrieve the file name from the file attributes that I want to show to the users. 

Currently I've just extended the `GoogleDriveAdapter` class and overrode `normaliseObject` method to always set `$result['display_path']` to `$this->toDisplayPath($result['virtual_path'])` regardless of the `useDisplayPaths` setting, but is there a better way to do it? If not that would be my feature request

**Comment by erikn69** [comment]
Look at this, that functionality was removed
https://github.com/masbug/flysystem-google-drive-ext/commit/f9a69eefe01d0c8f78dd191c9c540740ade94735
https://github.com/masbug/flysystem-google-drive-ext/blob/3947d39be212bff9cea95b2a5252e52c9eb36cc0/src/GoogleDriveAdapter.php#L1175-L1181

**Comment by jacekkarczmarczyk** [comment]
I know it's removed, that's why I've created this issue to add it back. Also these lines are the lines I've fixed in my class. 

What was the reason for removing the possibility to access the display path?

**Comment by erikn69** [comment]
Ask here https://github.com/masbug/flysystem-google-drive-ext/pull/61
