### ISSUE TITLE
Hooking into the cache

### ISSUE THREAD

**Issue by Mark-H** [masbug/flysystem-google-drive-ext#85]
Thanks for your work on this driver :) 

The adapter seems to be requesting all root files when initializing, which is quite the performance impact. Now, it does do a lot of in-memory caching, however, that cache is gone with the next request. 

I've looked through the code, but is there supposed to be a way to hook into this cache to somehow persist it in my app's cache and restore the driver with pre-fetched data?

**Comment by masbug** [comment]
> The adapter seems to be requesting all root files when initializing, which is quite the performance impact. Now, it does do a lot of in-memory caching, however, that cache is gone with the next request.

The problem is that you start with an ID and for that ID you get children ID's ...so you don't really know which one to choose and you have to query them all.

> I've looked through the code, but is there supposed to be a way to hook into this cache to somehow persist it in my app's cache and restore the driver with pre-fetched data?

No. You could try caching variables cleared in "clearCache" function...but this could work only in a single app, single user environment.
