### ISSUE TITLE
Login Issue Header

### ISSUE THREAD

**Issue by zainawan99** [masbug/flysystem-google-drive-ext#86]
![image](https://user-images.githubusercontent.com/24542584/198501168-74b309b3-4c6a-491f-ab0a-4177b05815b5.png)

**Comment by angeljqv** [comment]
You need client id, secret and refresh token

**Comment by zainawan99** [comment]
> You need the client id, secret, and refresh token

I have followed allow steps you have provide but they have shown this error

**Comment by zainawan99** [comment]
i more thing same client id and secret used in google play oauth they have worked fine.

**Comment by angeljqv** [comment]
Did you try this demo? 
https://github.com/erikn69/laravel-google-drive-ext-demo
