### ISSUE TITLE
Dir sharing issue

### ISSUE THREAD

**Issue by kovspace** [masbug/flysystem-google-drive-ext#88]
Method url() publish folder but do not return the link.
Link has the next template:
`'https://drive.google.com/drive/folders/' . $id . '?usp=sharing'`

**Comment by parallels999** [comment]
If you give almost no information you will get no answers

**Comment by kovspace** [comment]
`Storage::disk('google')->url($path);`
not working if path is folder

**Comment by parallels999** [comment]
Google links is for files, not for folders

**Comment by parallels999** [comment]
Feel free to make a PR for improve that

**Comment by kovspace** [comment]
> Google links is for files, not for folders

But folder becomes public after it

**Comment by parallels999** [comment]
> Feel free to make a PR for improve that

That not was made for folders

**Comment by kovspace** [comment]
PR: https://github.com/masbug/flysystem-google-drive-ext/pull/89/files

**Comment by masbug** [comment]
Merged.
