### ISSUE TITLE
When uploading a file to a shared folder, the file doesn't end up in the desired destination. 

### ISSUE THREAD

**Issue by austinkregel** [masbug/flysystem-google-drive-ext#90]
Greetings! 

Thank you for your work on this extension! My team has been using the 1.x version for the last number of years, and recently released our upgrade to Laravel 9.x and the 2.x version of this package on the 14th of December.

We were alerted to an issue, where none of our reports have uploaded to a shared Google Drive folder since December 14th, on the 19th. I've been debugging it for the last day and I believe I've narrowed down the scope/cause to our upgrade to the 2.x version of this package

## Setup

Our application uploads various reports to different FTP servers and a few Google Drive Folders. Our file systems can be summarised by 
```php
'google_drive_vendor' => [
  'driver' => 'google_drive',
  'root' => env('REPORT_FOLDER_ID'),
  'subject' => env('GOOGLE_DRIVE_USER', 'automation@company.com'),
  'service_account' => 'company-service-account'
],
```
The `REPORT_FOLDER_ID` is set to a value that looks similar to this (changed for privacy) `8KtgBylU4qfGRybyz0zbJSYqBrGRpp-dp`. The value for a folder labeled `Metrics`, and owned by our VP of Engineering. The account that uploads the file is an automations account on our account used for our reporting. 

## Expectations

Before we upgraded to the 2.x version, our automation user would be able to successfully upload to the shared folder.

Using the previously mentioned report folder id as an example: This would upload a file to the folder with the ID `8KtgBylU4qfGRybyz0zbJSYqBrGRpp-dp`, in this case a folder named `Metrics`, so the path should be `/Metrics/file.txt` -> Within shared folder

## Current Behavior

With this upgrade to 2.x, our automation user is creating its own folder (not shared) labeled after the ID of the desired folder. 
Using the previously mentioned report folder id as an example: it would create a folder named `8KtgBylU4qfGRybyz0zbJSYqBrGRpp-dp`, and within that folder it uploads our files, instead of uploading to the folder that has that as its ID, in this case a folder named `Metrics`, so the path ends up being `/8KtgBylU4qfGRybyz0zbJSYqBrGRpp-dp/file.txt` -> Within the `automation@company.com`'s drive folder.

## Questions?

 - Is this functionality intentional? I don't see an explicit mention to uploading to shared drive folders, I saw this issue, but after attempting to upload a file with the changes made in the suggested PR, our problem persisted with the current behavior.
 - Is there a way to accomplish the expected behavior without reverting to 2.x? (I imagine we're missing some kind of config option, but am not entirely sure)
 - I'd love to help contribute! Is there anything I should know before attempting to submit a PR for a fix? (Like preferred coding patterns for the package, or a preferred way to test?)

**Comment by erikn69** [comment]
**Seems like a question for discussions section, no on issues section**

Google change how shared drives works

- https://developers.google.com/drive/api/v3/reference/files/list
- https://github.com/masbug/flysystem-google-drive-ext/pull/62
- https://github.com/masbug/flysystem-google-drive-ext/issues/57#issuecomment-1078186012
- https://github.com/erikn69/laravel-google-drive-ext-demo/issues/1#issuecomment-1069279282

If you think that there is a bug please share an example to replicate it

**Comment by austinkregel** [comment]
This is a bug to the best of my knowledge, this is not a shared drive I stated several times it's a shared folder. You made a comment on [Working with Shared Drives](https://github.com/erikn69/laravel-google-drive-ext-demo/issues/1#issuecomment-1069279282), that using a shared folder should work the same as a regular folder. 

I have this Folder in my drive (my personal gmail), and I'm sharing it with my work email with edit permissions (a gsuite account).
![image](https://user-images.githubusercontent.com/5355937/209197623-5c304a96-fd25-4c68-9836-9bca5fc01bdd.png)


I attempted to use it like a regular folder, and it's creating a folder by that name on the account used to perform the action. (In this case I'm using my gsuite account to perform the uploads)
![image](https://user-images.githubusercontent.com/5355937/209196225-b6f76a7a-908e-45b5-b3f8-2fb2c24fae93.png)


When attempting to use the following code to upload the file to that shared folder,

```php
Artisan::command('test', function () {
    dd(\Illuminate\Support\Facades\Storage::disk('reporting-folder')->put('hello', 'hello'));
});
```

this package instead creates a folder under my work email account instead of uploading to the shared folder.
![image](https://user-images.githubusercontent.com/5355937/209198081-5f44ae4c-6e9f-437e-ae01-d15b6c6a5ba4.png)

When attempting to use the ID of the folder like our production account does with `automate@company.com`
![image](https://user-images.githubusercontent.com/5355937/209198348-681e4898-edb3-48bd-8efd-870ebfc7df82.png)
This package creates a folder by the name of the folder ID instead of uploading to the expected shared folder.
![image](https://user-images.githubusercontent.com/5355937/209198470-8396d81a-666e-4ac8-b930-f79828b8ad8c.png)

Keeping the configuration of using the folder ID to upload the file, I reverted our app back to the 1.x version of this package. I ran the same test command to upload a file to the folder and this time it uploaded to the shared folder as expected instead of creating a folder.
![image](https://user-images.githubusercontent.com/5355937/209198893-ae1e8e2f-1033-4624-a7b4-7c07228c19b8.png)

Based on everything I've seen talked about in the issues, in the readme, and in the discussion says that the behavior of 2.x in this particular case should be the same as 1.x, unless I'm misunderstanding here.

**Comment by erikn69** [comment]
Seems like you didn't read the example
https://github.com/masbug/flysystem-google-drive-ext#add-disks-on-configfilesystemsphp
There is no `root` on the config

Follow documentation exactly or please share an example to replicate it

From 1.x to 2.x there are many breaking changes, all because [flysystems](https://github.com/thephpleague/flysystem) changes from 1.x to 3.x

I have no problems with shared folders

Also you can test this demo: https://github.com/erikn69/laravel-google-drive-ext-demo

Did you try not putting anything in the `root` propertie?

**Comment by austinkregel** [comment]
I did read the example, but the specific change to not using `root` is wholly dependant on how you implement the driver. In this case the change of the array key is arbitrary and does not impact the expected functionality.

Here's how our app builds the google client.
![image](https://user-images.githubusercontent.com/5355937/209232227-26b833a0-e812-468b-a3f3-44d817bb29ef.png)

Here's how we're binding it:
![image](https://user-images.githubusercontent.com/5355937/209232732-e61b7ef1-ffb1-45c5-91dd-cd474308d779.png)

And here's how we're creating the driver
![image](https://user-images.githubusercontent.com/5355937/209230931-88821b94-fa1c-40e7-98e7-0af9776b95d7.png)


I have changed the `root` property to folder, and the resulting behavior is the exact same as I described in my first and second posts.

**Comment by erikn69** [comment]
Sorry i can't replicate your problem, make a failing test or a failing demo on fresh installation
Run the tests on your shared folder [GoogleDriveAdapterTests.php](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/tests/GoogleDriveAdapterTests.php)

In addition, your implementation is not the usual one, I cannot deduce that it could be failing

**Comment by austinkregel** [comment]
Okay, I'll be working on a reproducible test case first thing Tuesday morning (when my office is open again).

**Comment by austinkregel** [comment]
I come with a little bit of information. The behavior my team is specifically experiencing appears to be the same as if you were to try to upload to a folder that doesn't exist. Previously such an act would cause exceptions to be thrown, however, it's catching the exception and creating the folder it thinks should be there

After a lot of debugging with Xdebug, I've [been able to pinpoint the behavior we're experiencing](https://github.com/masbug/flysystem-google-drive-ext/blob/1.x/src/GoogleDriveAdapter.php#L2016), and for us, it's unexpected behavior for us however it looks like expected behavior for this library.

Here are the sequence of events our system ends up going through

 - When a new instance of the driver is created, [the system attempts to find the single virutal path](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/src/GoogleDriveAdapter.php#L284) of the root folder, which is the second argument of the class constructor.
 - Within the constructor, if you're not using a shared team drive, is a call to [`toVirtualPath`, and it attempts to look up the folder in the class's cache](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/src/GoogleDriveAdapter.php#L2046) by the name passed. Since we're working with a shared folder, we're using folder Ids.
 - The folder, not having been cached, is [throwing the exception on line 2006](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/src/GoogleDriveAdapter.php#L2006) essentially saying the folder/path doesn't exist.
 - Since the 4th argument in the constructor mentioned in 1. is `true`, [when the driver catchs the exception it attempts to create the root directory](https://github.com/masbug/flysystem-google-drive-ext/blob/2.x/src/GoogleDriveAdapter.php#L2063)
 - Since my team gives it an ID instead of the folder, it creates the ID as the root folder, instead of identifying the shared folder.
 - Then when attempting to upload, it already has that cached folder, so it uploads the file there instead of to the shared folder.
 
After looking through the library's code, it seems like creating a missing folder is intended functionality here. That being the case I've advised my team that we should move to a shared drive instead of relying on shared folders.

I've tested our use with a shared drive, and new folder names (instead of IDs) and everything appeared to work as expected, our files ended up in the shared drive instead of getting lost in our automation's account.

**Comment by parijke** [comment]
I am experiencing the same, and I have no option to use a shared drive. Is there any direction how to solve this using shared folders instead?

**Comment by parallels999** [comment]
@parijke hi, feel free to make a pull request if you think that it's a bug

**Comment by MRHRTZ** [comment]
Hi, if you still can't upload in shared folder here I have tested it.

Add this option to `boot function` in `app/Providers/GoogleServiceProvider.php`
```php
$options['useDisplayPaths'] = false;
```

could look like this
```php
public function boot(): void
    {
        try {
            Storage::extend('google', function($app, $config) {
                $options = [];
                $options['useDisplayPaths'] = false;

                if (!empty($config['teamDriveId'] ?? null)) {
                    $options['teamDriveId'] = $config['teamDriveId'];
                }

                $client = new \Google\Client();
                $client->setClientId($config['clientId']);
                $client->setClientSecret($config['clientSecret']);
                $client->refreshToken($config['refreshToken']);
                
                $service = new \Google\Service\Drive($client);
                $adapter = new \Masbug\Flysystem\GoogleDriveAdapter($service, $config['folder'] ?? '/', $options);
                $driver = new \League\Flysystem\Filesystem($adapter);

                return new \Illuminate\Filesystem\FilesystemAdapter($driver, $adapter);
            });
        } catch (\Exception $e) {
            Log::error($e);
        }
    }
```

Then just use shared folder id to your `.env`
```env
GOOGLE_DRIVE_CLIENT_ID=xxx.apps.googleusercontent.com
GOOGLE_DRIVE_CLIENT_SECRET=xxx
GOOGLE_DRIVE_REFRESH_TOKEN=xxx
GOOGLE_DRIVE_FOLDER=1GDxXxjT_ohPQtkm5lhK9CAbpxQae5lfO
```

That option will override to use IDs instead of display path.
