### ISSUE TITLE
Move Shared Drive file to a folder

### ISSUE THREAD

**Issue by badcom** [masbug/flysystem-google-drive-ext#95]
I've got this simple Shared Drive structure:

Shared Drive
    Folder 1
    Folder 2
    Folder 3

I'd like to create a file in one of the folders within that Shared Drive i.e.: Folder 1, Folder 2, etc.

Is it possible to define which folder I want to create the file in? Preferably by passing the folder name instead of the folder ID.

I already can create files in that Shared Drive, but I'd like to be able to create them in specific folders within that Shared Drive.

Hope that makes sense :)

**Comment by parallels999** [comment]
> Is it possible to define which folder I want to create the file in? Preferably by passing the folder name instead of the folder ID.

That is exactly what this package does. Didn't you read the specs?

**Comment by parallels999** [comment]
Also use discussions section for this kind of topics, that is not an issue
