### ISSUE TITLE
cannot list directory shortcuts

### ISSUE THREAD

**Issue by markymarrow** [masbug/flysystem-google-drive-ext#96]
In My Google Drive I have a number of shortcuts to directories that have been shared with me.
I need to be able to upload files into these shared folders but currently
`Storage::disk('google')->listContents('the-shortcut')` just returns []

I've worked around it by forking the code and adding shortcutDetails to FETCHFIELDS_LIST and adding

```
if ($object->mimeType == self::SHORTCUTMIME) {
    $object->mimeType = $object->shortcutDetails->targetMimeType;
    $id = $object->shortcutDetails->targetId;
}
```
near the top of normaliseObject.
but it feels too easy & I wonder what I might be missing

**Comment by parallels999** [comment]
Feel free to make a PR, thanks

**Comment by masbug** [comment]
Merged.
